apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ride-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-ride
  template:
    metadata:
      labels:
        app: ms-ride
    spec:
      containers:
        - image: gh6987/rso:ms-ride-2023-12-05-17-16-35 #to be changed
          name: ms-ride
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/wvgniptg
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: wvgniptg
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: ms-ride
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ms-ride