apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ride-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-ride
  template:
    metadata:
      labels:
        app: ms-ride
    spec:
      containers:
        - image: repo_iz_dockerhuba/ms-ride:test #to be changed
          name: ms-ride
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: #connection url
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: #username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              #value: #password
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: #to be added
                  key: #to be added
          ports:
            - containerPort: 8080
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: ms-ride
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ms-ride