kumuluzee:
  name: ms-ride-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/RideDataDS
      connection-url: jdbc:postgresql://localhost:5432/msride
      username: wvgniptg
      password: pqJ1wX3BPdwlvTBWEEnSM2klLIbZufyx
      pool:
        max-size: 4
  dev:
    scan-libraries:
      - ms-ride-models
      - ms-ride-services
      - ms-ride-lib
  openapi-mp:
    ui:
      specification-server: http://20.253.101.2/ms-ride
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RideDataDS
    metrics:
      web-instrumentation:
        - name: rides-endpoint
          url-pattern: /v1/rides/*
    logs:
      config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="rides">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="2a983b5d-6bb9-4003-b231-bcf3b3fb6c6a-ls.logit.io"
                                      port="16378" protocol="udp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="trace" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'
rest-properties:
  broken: false
town-api:
  url: https://teaching.lavbic.net/api/kraji/vsi